config/routes.rb
Rails.application.routes.draw do
  root :to => 'cars#index'
  resources :users, :only => [:index, :new, :create]
  resources :cars
  resources :trims
  resources :manufacturers
  resources :engines

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord
    belongs_to :user, :optional => true
    belongs_to :engine, :optional => true
    has_many :trims
    belongs_to :manufacturer, :optional => true
end

app/models/engine.rb
class Engine < ApplicationRecord
    has_many :cars
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
    has_many :cars
    has_many :engines, :through => :cars
end

app/models/trim.rb
class Trim < ApplicationRecord
    belongs_to :car, :optional => true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, :uniqueness => true, :presence => true
    has_many :cars
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user

    private
    def fetch_user
        @current_user = User.find_by :id => session[:user_id]
        session[:user_id] = nil unless @current_user.present?
    end

    def check_for_login
        redirect_to login_path unless @current_user.present?
    end

    def check_for_admin
        redirect_to login_path unless (@current_user.present? && @current_user.admin?)
    end
    
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :check_for_login

  def index
    # @cars = Car.all
    @cars = @current_user.cars.all
  end

  def new
    @car = Car.new
  end

  def create
    car = @current_user.cars.create car_params
    if params[:file].present?
        req = Cloudinary::Uploader.upload(params[:file])
        car.image = req["public_id"]
        car.save
    end
    redirect_to root_path
  end

  def edit
    @car = Car.find params[:id]
  end

  def update
    car = @current_user.cars.find params[:id]
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      car.image = req["public_id"]
    end
    car.update_attributes car_params
    car.save
    redirect_to car_params
  end

  def show
    @car = Car.find params[:id]
    unless @car.trims.where(id: params[:id]).empty?
    @trim = @car.trims.find params[:id]
    end
    # end
  end

  def destroy
    car = @current_user.cars.find params[:id]
    car.destroy
    redirect_to root_path
  end

  private
  def car_params
    params.require(:car).permit(:name, :image, :manufacturer_id, :trim_id, :engine_id)
  end
end

app/controllers/engines_controller.rb
class EnginesController < ApplicationController
    before_action :check_for_login

    def index
      @engines = Engine.all
    end
  
    def new
      @engine = Engine.new
    end
  
    def create
      engine = Engine.create engine_params
      if params[:file].present?
          req = Cloudinary::Uploader.upload(params[:file])
          engine.image = req["public_id"]
          engine.save
      end
      redirect_to engine
    end
  
    def edit
      @engine = Engine.find params[:id]
    end
  
    def update
      engine = Engine.find params[:id]
      if params[:file].present?
        req = Cloudinary::Uploader.upload(params[:file])
        engine.image = req["public_id"]
      end
      engine.update_attributes engine_params
      engine.save
      redirect_to engine_params
    end
  
    def show
      @engine = Engine.find params[:id]
    end
  
    def destroy
      engine = Engine.find params[:id]
      engine.destroy
      redirect_to engine
    end
  
    private
    def engine_params
      params.require(:engine).permit(:name, :capacity, :hp, :torque, :mods, :image)
    end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  before_action :check_for_login

  def index
    @manufacturers = Manufacturer.all
  end

  def new
    @manufacturer = Manufacturer.new
  end

  def create
    manufacturer = Manufacturer.create manufacturer_params
    if params[:file].present?
        req = Cloudinary::Uploader.upload(params[:file])
        manufacturer.image = req["public_id"]
        manufacturer.save
    end
    redirect_to manufacturer
  end

  def edit
    @manufacturer = Manufacturer.find params[:id]
  end

  def update
    manufacturer = Manufacturer.find params[:id]
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      manufacturer.image = req["public_id"]
    end
    manufacturer.update_attributes manufacturer_params
    manufacturer.save
    redirect_to manufacturer_params
  end

  def show
    @manufacturer = Manufacturer.find params[:id]
  end

  def destroy
    manufacturer = Manufacturer.find params[:id]
    manufacturer.destroy
    redirect_to manufacturer
  end

  private
  def manufacturer_params
    params.require(:manufacturer).permit(:name, :image, :founded, :location)
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash[:error] = "Invalid username or password"
      redirect_to login_path
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path
  end

end

app/controllers/trims_controller.rb
class TrimsController < ApplicationController
  before_action :check_for_login

  def index
    @trims = Trim.all
  end

  def new
    # car = Car.find(params[:id])
    # trim = car.trim
    @trim = Trim.new
  end

  def create
    @car = Car.find(params[:car_id])
    @trim = @car.trims.build(trim_params)
    # trim = Trim.create trim_params
    if params[:file].present?
        req = Cloudinary::Uploader.upload(params[:file])
        @trim.image = req["public_id"]
        @trim.save
    end
    redirect_to new_car_trim_path(@car)
  end

  def edit
    @trim = Trim.find params[:id]
  end

  def update
    @car = Car.find(params[:car_id])
    @trim = @car.trims.build(trim_params)
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      trim.image = req["public_id"]
    end
    trim.update_attributes trim_params
    trim.save
    redirect_to trim_params
  end

  def show
    # car = Car.find(params[:id])
    # @trim = car.trims.find(params[:id])
    @trim = Trim.find params[:id]
  end

  def destroy
    trim = Trim.find params[:id]
    trim.destroy
    redirect_to root_path
  end

  private
  def trim_params
    params.require(:trim).permit(:color, :wheel_size, :wheel_mat, :interior, :sport, :int_color, :image, :features)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_for_admin, :only => [:index]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.create user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/engines_helper.rb
module EnginesHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/trims_helper.rb
module TrimsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/_form.html.erb
<div class="container">
<%= form_for(@car, :html => { :multipart => true}) do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control", :placeholder => "Mustang" %>

    <%= f.label :manufacturer_id %>
    <%= f.select :manufacturer_id, Manufacturer.pluck(:name, :id), :include_blank => true, :class => "form-control" %>

    <%= f.label :engine_id %>
    <%= f.select :engine_id, Engine.pluck(:name, :id), :include_blank => true, :class => "form-control" %>
    
    <%= f.label :image %>
    <%= f.cl_image_upload :image_url, :class => "form-control" %>
    <p></p>

    <%= f.submit :class => "btn btn-primary" %>

<% end %>
</div>

app/views/cars/edit.html.erb
<h1>Edit Car</h1>
<%= render :partial => 'form' %>

app/views/cars/index.html.erb
<h1>All Cars</h1>

<div class="container">
<h1>All Cars</h1>
-----------------------------------------------------------------------------------------------------------------------------------
    <div class="row">
        <% @cars.each do |car| %>

        <div class="col-sm-8 col-md-4 col-lg-6">
        <h2><%= car.name %></h2>
        <% if car.image.present? %>
            <% if car.image.start_with?('/image') %>
                <%= link_to image_tag(car.image, skip_pipeline: true, class: "card-img-top img-fluid"), car %>
            <% else %>
            <%= link_to cl_image_tag(car.image, class: "card-img-top img-fluid"), car %>
            <% end %>
        <% else %>
            <%= link_to image_tag('https://picsum.photos/500', class: "card-img-top img-fluid"), car %>
        <% end %>
        </div>
        <% end %>
        
    </div>
</div>

app/views/cars/new.html.erb
<h1>New Car</h1>
<%= render :partial => 'form' %>

app/views/cars/show.html.erb
<div class="container">
<h1><%= @car.name %></h1>

  <% if @car.image.present? %>
    <% if @car.image.start_with?('/image') %>
        <%= image_tag(@car.image, skip_pipeline: true, class: 'feature') %>
    <% else %>
      <%= cl_image_tag(@car.image, class: 'feature') %>
    <% end %>
  <% else %>
    <%= image_tag('https://picsum.photos/500', class: 'feature') %>
  <% end %>

<ul>

    <li>Manufacturer: <%= link_to @car.manufacturer.name, @car.manufacturer unless @car.manufacturer.nil? %></li>
    <% if @trim.nil? %>
    <li>Add Trim: <%= link_to 'add', new_trim_path %></li>
    <% else %>
    <li><%= link_to 'Car model features', @trim %></li>
    <% end %>
    <%# -------------------------------------------------------------- #%>



    <%# -------------------------------------------------------------- #%>
    <li>Engine: <%= link_to @car.engine.name, @car.engine unless @car.engine.nil? %></li>

</ul>

<div class="controls">
    <%= link_to "Edit car", edit_car_path(@car), :class => "btn btn-primary" %>
    <%= link_to "Delete car", @car, :class => "btn btn-primary", :method => :delete, :data => { :confirm => "Are your sure?" } %>
</div> 
</div>

app/views/engines/_form.html.erb
<div class="container">
<%= form_for(@engine, :html => { :multipart => true}) do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>

    <%= f.label :capacity %>
    <%= f.text_field :capacity, :class => "form-control" %>

    <%= f.label :hp %>
    <%= f.text_field :hp, :class => "form-control" %>

    <%= f.label :torque %>
    <%= f.text_field :torque, :class => "form-control" %>

    <%= f.label :mods %>
    <%= f.text_field :mods, :class => "form-control" %>

    <%= f.label :image %>
    <%= f.cl_image_upload :image_url, :class => "form-control" %>

    <p></p>
    <%= f.submit :class => "btn btn-primary" %>

<% end %>
</div>

app/views/engines/edit.html.erb
<h1>Edit Engine</h1>
<%= render :partial => 'form' %>

app/views/engines/index.html.erb
<h1>All Engines</h1>

<div class="container">
<h1>All Engines</h1>
-----------------------------------------------------------------------------------------------------------------------------------
    <div class="row">
        <% @engines.each do |engine| %>

        <div class="col-sm-6 col-md-4 col-lg-6">
            <h2><%= engine.name %></h2>
            <% if engine.image.present? %>
                <% if engine.image.start_with?('/image') %>
                    <%= link_to image_tag(engine.image, skip_pipeline: true, class: "card-img-top img-fluid"), engine %>
                <% else %>
                    <%= link_to cl_image_tag(engine.image, class: "card-img-top img-fluid"), engine %>
                <% end %>
            <% else %>
                <%= link_to image_tag('https://picsum.photos/500', class: "card-img-top img-fluid"), engine %>
            <% end %>
        </div>
        <% end %>
    </div>
</div>

app/views/engines/new.html.erb
<h1>New Engine</h1>
<%= render :partial => 'form' %>

app/views/engines/show.html.erb
<div class="container">
<h1><%= @engine.name %></h1>

    <% if @engine.image.start_with?('/image') %>
        <%= image_tag(@engine.image, skip_pipeline: true, class: 'feature') %>
    <% else %>
      <%= cl_image_tag(@engine.image, class: 'feature') %>
    <% end %>

<ul>

    <li>Engine Size: <%= @engine.capacity %>cc</li>
    <li>Power: <%= @engine.hp %>hp and <%= @engine.torque %>nm of torque</li>
    <li>additional features: <%= @engine.mods %></li>

</ul>

<div class="controls">
    <%= link_to "Edit engine", edit_engine_path(@engine), :class => "btn btn-primary" %>
    <%= link_to "Delete engine", @engine, :class => "btn btn-primary", :method => :delete, :data => { :confirm => "Are your sure?" } %>
</div> 

<h1>All Favourite cars which include <%= @engine.name %></h1>

<div class="row">
    <% @engine.cars.each do |car| %>

    <div class="col-sm-8 col-md-4 col-lg-6">
    <h2><%= car.name %></h2>
    <% if car.image.present? %>
        <% if car.image.start_with?('/image') %>
            <%= link_to image_tag(car.image, skip_pipeline: true, class: "card-img-top img-fluid"), car %>
        <% else %>
        <%= link_to cl_image_tag(car.image, class: "card-img-top img-fluid"), car %>
        <% end %>
    <% else %>
        <%= link_to image_tag('https://picsum.photos/500', class: "card-img-top img-fluid"), car %>
    <% end %>
    </div>
    <% end %>
    
</div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
    
  </head>

  <body>
    
    <nav class="navbar navbar-dark bg-dark fixed-top">
      <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarContent">
              <ul class="navbar-nav">
              <% if @current_user.present? %>
                  <% if @current_user.admin? %>
                  <li class="nav-item">
                      <a class="nav-link"><%= link_to "All users", users_path %></a>
                  </li>
                  <% end %>
                  <li class="nav-item">
                      <a class="nav-link"><%= link_to "All Cars", cars_path %></a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link"><%= link_to "New Car", new_car_path %></a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link"><%= link_to "All Manufacturers", manufacturers_path %></a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link"><%= link_to "New Manufacturer", new_manufacturer_path %></a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link"><%= link_to "All Engines", engines_path %></a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link"><%= link_to "New Engine", new_engine_path %></a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link"><%= link_to "Log out: #{ @current_user.email }", login_path, :method => :delete %></a>
                  </li>
              <% else %>
                  <li class="nav-item">
                      <a class="nav-link"><%= link_to "Sign up!", new_user_path %></a>
                  </li>
                  <li class="nav-item">
                      <a class="nav-link"><%= link_to "Sign in!", login_path %></a>
                  </li>
              <% end %>
              </ul>
          </div>
      </div>
    </nav>
    
    <%= yield %>

    </div>
  </body>

  <script>
  $(document).ready(function(){
    $('.navbar-toggler').click(function(){
      $('.navbar-collapse').toggleClass('show');
    });
    // $('.navbar-toggler').click(function(){
    //   $('.navbar-collapse').toggleClass('show collapsing');
    // });
  });
  </script>

</html>

app/views/manufacturers/_form.html.erb
<div class="container">
<%= form_for(@manufacturer, :html => { :multipart => true}) do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>

    <%= f.label :founded %>
    <%= f.text_field :founded, :class => "form-control" %>

    <%= f.label :location %>
    <%= f.text_field :location, :class => "form-control" %>
    
    <%= f.label :image %>
    <%= f.cl_image_upload :image_url, :class => "form-control" %>

    <p></p>
    <%= f.submit :class => "btn btn-primary" %>

<% end %>
</div>

app/views/manufacturers/edit.html.erb
<h1>Edit Manufacturer</h1>
<%= render :partial => 'form' %>

app/views/manufacturers/index.html.erb
<h1>All Manufacturers</h1>

<div class="container">
<h1>All Manufacturers</h1>
-----------------------------------------------------------------------------------------------------------------------------------
    <div class="row">
        <% @manufacturers.each do |manufacturer| %>

        <div class="col-sm-6 col-md-4 col-lg-6">
            <% if manufacturer.image.present? %>
                <% if manufacturer.image.start_with?('/image') %>
                    <%= link_to image_tag(manufacturer.image, skip_pipeline: true, class: "card-img-top img-fluid"), manufacturer %>
                <% else %>
                    <%= link_to cl_image_tag(manufacturer.image, class: "card-img-top img-fluid"), manufacturer %>
                <% end %>
            <% else %>
                <%= link_to image_tag('https://picsum.photos/500', class: "card-img-top img-fluid"), manufacturer %>
            <% end %>
        </div>
        <% end %>
    </div>
</div>

app/views/manufacturers/new.html.erb
<h1>New Manufacturer</h1>
<%= render :partial => 'form' %>

app/views/manufacturers/show.html.erb
<div class="container">
<h1><%= @manufacturer.name %></h1>

<% if @manufacturer.image.present? %>
<% if @manufacturer.image.start_with?('/image') %>
        <%= image_tag(@manufacturer.image, skip_pipeline: true, class: 'feature') %>
    <% else %>
      <%= cl_image_tag(@manufacturer.image, class: 'feature') %>
    <% end %>
<% end %>

<ul>

    <li>Date when Company was founded: <%= @manufacturer.founded.strftime "%A, %B #{@manufacturer.founded.day.ordinalize}, %Y" %></li>
    <li>Location where company was founded: <%= @manufacturer.location %></li>

</ul>

<div class="controls">
    <%= link_to "Edit manufacturer", edit_manufacturer_path(@manufacturer), :class => "btn btn-primary" %>
    <%= link_to "Delete manufacturer", @manufacturer, :class => "btn btn-primary", :method => :delete, :data => { :confirm => "Are your sure?" } %>
</div> 

<h1>All favourite cars made by <%= @manufacturer.name %></h1>

<div class="row">
    <% @manufacturer.cars.each do |car| %>

    <div class="col-sm-8 col-md-4 col-lg-6">
    <h2><%= car.name %></h2>
    <% if car.image.present? %>
        <% if car.image.start_with?('/image') %>
            <%= link_to image_tag(car.image, skip_pipeline: true, class: "card-img-top img-fluid"), car %>
        <% else %>
        <%= link_to cl_image_tag(car.image, class: "card-img-top img-fluid"), car %>
        <% end %>
    <% else %>
        <%= link_to image_tag('https://picsum.photos/500', class: "card-img-top img-fluid"), car %>
    <% end %>
    </div>
    <% end %>
    
</div>


</div>

app/views/session/new.html.erb
<div class="container">
<h1>Login</h1>

<% if flash[:error].present? %>
    <h2><%= flash[:error] %></h2>
<% end %>

<%= form_tag login_path do %>
    <%= label_tag :email, nil, :class => 'form-label' %>
    <%= email_field_tag :email, nil, :class => 'form-control' %>

    <%= label_tag :password, nil, :class => 'form-label' %>
    <%= password_field_tag :password, nil, :class => 'form-control' %>

    <%= submit_tag "Sign in", :class => 'btn btn-success btn-lg' %>
<% end %>
</div>

app/views/trims/_form.html.erb
<div class="container">
<%= form_with(model: [@car, @trim], :html => { :multipart => true }) do |f| %>

    <%= f.label :color %>
    <%= f.text_field :color, :class => "form-control" %>

    <%= f.label :wheel_size %>
    <%= f.text_field :wheel_size, :class => "form-control" %>

    <%= f.label :wheel_mat %>
    <%= f.text_field :wheel_mat, :class => "form-control" %>

    <%= f.label :interior %>
    <%= f.text_field :interior, :class => "form-control" %>

    <%= f.label :sport %>
    <%= f.text_field :sport, :class => "form-control" %>

    <%= f.label :int_color %>
    <%= f.text_field :int_color, :class => "form-control" %>

    <%= f.label :features %>
    <%= f.text_field :features, :class => "form-control" %>
    
    <%= f.label :image %>
    <%= f.cl_image_upload :image_url, :class => "form-control" %>
    <p></p>

    <%= f.submit :class => "btn btn-primary" %>

<% end %>
</div>

app/views/trims/edit.html.erb
<h1>Edit Trim</h1>
<%= render :partial => 'form' %>

app/views/trims/index.html.erb
bruhh

app/views/trims/new.html.erb
<h1>New Trim</h1>
<%= render :partial => 'form' %>

app/views/trims/show.html.erb
<div class="container">
<% if @trim.image.present? %>
<% if @trim.image.start_with?('/image') %>
        <%= image_tag(@trim.image, skip_pipeline: true, class: 'feature') %>
    <% else %>
      <%= cl_image_tag(@trim.image, class: 'feature') %>
    <% end %>
<% end %>

<ul>

    <li>Color: <%= @trim.color %></li>
    <li>Wheels: <%= @trim.wheel_size %> inch <%= @trim.wheel_mat %> wheels</li>
    <li>Interior: <%= @trim.int_color %> <%= @trim.interior %></li>
    <li><%= @trim.sport %></li>
    <li>Additional features: <%= @trim.features %></li>

</ul>

<div class="controls">
    <%= link_to "Edit trim", edit_trim_path(@trim), :class => "btn btn-primary" %>
    <%= link_to "Delete trim", @trim, :class => "btn btn-primary", :method => :delete, :data => { :confirm => "Are your sure?" } %>
</div> 
</div>

app/views/users/index.html.erb
<h1>All users</h1>

<% @users.each do |user| %>
    <p><%= user.email %></p>
<% end %>

app/views/users/new.html.erb
<div class="container">
<h1>Sign up!</h1>

<% if @user.errors.any? %>
    <ol>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ol>
<% end %>
<%= form_for @user do |f| %>
    <%= f.label :email, :class => 'form-label' %>
    <%= f.email_field :email, :class => 'form-control' %>

    <%= f.label :password, :class => 'form-label' %>
    <%= f.password_field :password, :class => 'form-control' %>

    <%= f.label :password_confirmation, :class => 'form-label' %>
    <%= f.password_field :password_confirmation, :class => 'form-control' %>

    <%= f.submit "Sign up!", :class => 'btn btn-success btn-lg' %>
<% end %>
</div>